sudo: required
language: java
notifications:
  email:
  - vertx3-ci@googlegroups.com
jdk:
- oraclejdk8
branches:
  only:
  - master
env:
  global:
  - secure: l3ublNqqWPEjZh8Dfk92VMPtTY0HZgwLhO2zHyaok7GMXXq9LDUrLu1FYCQC3RG3uouGDQte50+rtl1t3rQRnKNSxsPxtPvMR1gZ/jGDv3slhgWYsdIbAT6zN0pgXXI8n58Ko0796lIFLRPpcMqUgezP1MsbG2XG3tcqAocpR3o=
  - secure: fAdnOYXeKglxbxZQ2yD4JWrzkwjvstAckbDldkanizKgO7ze6Refxc2UXCauxI35RvDy82FtD6zPtxI6DAYdWAAaFdUzPUi/1ATp0jDHVdkYRGBB2E2FSlI3sQRALyNefijeBpQh35/XZAxl9L02AexjIurcvZB1Rcn5UaaRHkQ=
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
install: true
script:
- travis_wait 30 mvn -q -Dmaven.test.redirectTestOutputToFile verify -B
after_success:
- PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -B | grep -v '\[')
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
    mvn deploy -DskipTests -B;
  fi
