sudo: required
language: java
notifications:
  email:
  - vertx3-ci@googlegroups.com
jdk:
- oraclejdk8
branches:
  only:
  - master
env:
  global:
  - SONATYPE_NEXUS_USERNAME: test_user
  - SONATYPE_NEXUS_PASSWORD: test_password
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
- mvn help:effective-settings
install: true
script:
- travis_wait 30 mvn -q -Dmaven.test.redirectTestOutputToFile verify -B
after_success:
- PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -B | grep -v '\[')
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
    mvn help:effective-settings;
    mvn deploy -DskipTests -B -X;
  fi
